version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - node-exporter
      - cadvisor
      - kafka-exporter
    networks:
      - monitoring-network
    restart: unless-stopped

  kafka-exporter:
    image: danielqsj/kafka-exporter
    command: --kafka.server=SERVER_URL:9092
    ports:
      - "9308:9308"
    networks:
      - monitoring-network
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - monitoring-network
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
    networks:
      - monitoring-network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
    - 6379:6379
    networks:
      - monitoring-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring-network
    restart: unless-stopped

volumes:
  grafana-storage:

networks:
  monitoring-network:
    external: true

