global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]

  - job_name: 'main-inference-app'
    static_configs:
      - targets: ['main-inference-app:3001']

  - job_name: 'nightly-inference-app'
    static_configs:
      - targets: ['nightly-inference-app:3002']
